# Real-world Data Wrangling

In this project, you will apply the skills you acquired in the course to gather and wrangle real-world data with two datasets of your choice.

You will retrieve and extract the data, assess the data programmatically and visually, accross elements of data quality and structure, and implement a cleaning strategy for the data. You will then store the updated data into your selected database/data store, combine the data, and answer a research question with the datasets.

Throughout the process, you are expected to:

1. Explain your decisions towards methods used for gathering, assessing, cleaning, storing, and answering the research question
2. Write code comments so your code is more readable

Before you start, install the some of the required packages.

In [157]:
!python -m pip install kaggle==1.6.12

Requirement already satisfied: kaggle==1.6.12 in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (1.6.12)
Requirement already satisfied: six>=1.10 in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from kaggle==1.6.12) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from kaggle==1.6.12) (2024.8.30)
Requirement already satisfied: python-dateutil in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from kaggle==1.6.12) (2.8.2)
Requirement already satisfied: requests in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from kaggle==1.6.12) (2.29.0)
Requirement already satisfied: tqdm in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from kaggle==1.6.12) (4.65.0)
Requirement already satisfied: python-slugify in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from kaggle==1.6.12) (5.0.2)
Requirement already satisfied: urllib3 in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from kaggle==1.6.12) (1.26.16)
Requirement already satisfied: bleach in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from kaggle==1.6.12) (4.1.0)
Requirement already satisfied: packaging in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from bleach->kaggle==1.6.12) (23.0)
Requirement already satisfied: webencodings in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from bleach->kaggle==1.6.12) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from python-slugify->kaggle==1.6.12) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from requests->kaggle==1.6.12) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/leonardoflores/anaconda3/lib/python3.11/site-packages (from requests->kaggle==1.6.12) (3.4)

In [158]:
import os 
import shutil

In [159]:
#Defined path for kaggle directory
kaggle_dir =os.path.expanduser('~/.kaggle')
#Create directory
os.makedirs(kaggle_dir, exist_ok=True)

In [160]:
#Move the kaggle.json file to the directory. updating the source path.
source_path = '/Users/leonardoflores/Downloads/kaggle.json'
destination_path = os.path.join(kaggle_dir, 'kaggle.json')

In [161]:
#Copying the kaggle.json to destination
shutil.copy(source_path, destination_path)

'/Users/leonardoflores/.kaggle/kaggle.json'

In [162]:
# Change permission to secure the file
os.chmod(destination_path, 0o600)

In [163]:
# Verify that the API worked
!kaggle datasets list

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.17 / client 1.6.12)
ref                                                           title                                            size  lastUpdated          downloadCount  voteCount  usabilityRating
------------------------------------------------------------  ----------------------------------------------  -----  -------------------  -------------  ---------  ---------------
muhammadroshaanriaz/students-performance-dataset-cleaned      Students Performance | Clean Dataset             10KB  2024-10-29 19:32:26           9803        179  1.0
ikynahidwin/depression-professional-dataset                   Depression Professional Dataset                  16KB  2024-11-20 06:39:18           1121         26  1.0
steve1215rogg/student-lifestyle-dataset                       student lifestyle dataset                        22KB  2024-11-11 19:11:28           4608         68  1.0
ikynahidwin/depression-student-dataset                        Depression Student Dataset                        4KB  2024-11-20 06:42:01           1186         29  1.0
jahnavipaliwal/field-of-study-vs-occupation                   Field Of Study vs Occupation                    817KB  2024-11-07 20:38:44           1640         28  1.0
valakhorasani/gym-members-exercise-dataset                    Gym Members Exercise Dataset                     22KB  2024-10-06 11:27:38          20068        282  1.0
jakewright/200k-youtube-channel-analytics                     200k YouTube Channel Analytics                    4MB  2024-11-13 16:31:28           1605         40  1.0
willianoliveiragibin/top-12-german-companies                  Top 12 German Companies                          23KB  2024-11-16 20:40:37            729         23  1.0
brsahan/vehicle-co2-emissions-dataset                         Vehicle CO2 Emissions Dataset                    88KB  2024-11-20 22:24:16            853         30  1.0
jacopoferretti/incomes-of-30k-usa-citizens                    Incomes of 30K USA Citizens                     468KB  2024-11-17 00:16:20           1170         25  1.0
computingvictor/transactions-fraud-datasets                   üí≥ Financial Transactions Dataset: Analytics     348MB  2024-10-31 21:29:56           4895         74  1.0
whisperingkahuna/footballers-with-50-international-goals-men  Footballers with 50+ International Goals [men]    3KB  2024-11-17 12:51:23           1330         28  1.0
valakhorasani/mobile-device-usage-and-user-behavior-dataset   Mobile Device Usage and User Behavior Dataset    11KB  2024-09-28 20:21:12          30137        564  1.0
michau96/internet-search-engine-worldwide                     Internet search engine popularity                 5KB  2024-11-10 17:45:09           1012         26  1.0
ironwolf437/laptop-price-dataset                              Laptop Price - dataset‚Äè                          25KB  2024-11-12 15:50:44           2402         45  1.0
taweilo/loan-approval-classification-data                     Loan Approval Classification Dataset            751KB  2024-10-29 04:07:34           5532         55  1.0
bhadramohit/india-air-quality-index2024-dataset               India Air Quality Index(2024) Dataset            41KB  2024-11-04 14:18:23            989         22  1.0
valakhorasani/bank-transaction-dataset-for-fraud-detection    Bank Transaction Dataset for Fraud Detection    102KB  2024-11-04 09:23:49           3040         59  1.0
iamtapendu/bird-strike-by-aircafts-data                       Bird Strikes in Aviation: Aircraft Collisions     1MB  2024-11-15 13:41:24            966         26  1.0
daniellopez01/credit-risk                                     credit_risk                                      13KB  2024-11-17 22:13:54           1144         32  1.0

In [164]:
import pandas as pd
import json

## 1. Gather data

In this section, you will extract data using two different data gathering methods and combine the data. Use at least two different types of data-gathering methods.

### **1.1.** Problem Statement
In 2-4 sentences, explain the kind of problem you want to look at and the datasets you will be wrangling for this project.

*FILL IN:*

### **1.2.** Gather at least two datasets using two different data gathering methods

List of data gathering methods:

- Download data manually
- Programmatically downloading files
- Gather data by accessing APIs
- Gather and extract data from HTML files using BeautifulSoup
- Extract data from a SQL database

Each dataset must have at least two variables, and have greater than 500 data samples within each dataset.

For each dataset, briefly describe why you picked the dataset and the gathering method (2-3 full sentences), including the names and significance of the variables in the dataset. Show your work (e.g., if using an API to download the data, please include a snippet of your code). 

Load the dataset programmtically into this notebook.

#### **Dataset 1**

Type: CSV file

Method: The data was gathered using the "API" method from "Kaggle.com" source.

Dataset variables:

*   *Variable 1 FILL IN* (e.g., H_MEAN: Mean hourly wage)
*   *Variable 2 FILL IN*

In [165]:
! kaggle datasets list -s 'TMDB'

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.17 / client 1.6.12)
ref                                                      title                                                size  lastUpdated          downloadCount  voteCount  usabilityRating
-------------------------------------------------------  --------------------------------------------------  -----  -------------------  -------------  ---------  ---------------
tmdb/tmdb-movie-metadata                                 TMDB 5000 Movie Dataset                               9MB  2017-09-28 01:09:12         392482       3880  0.8235294
asaniczka/tmdb-movies-dataset-2023-930k-movies           Full TMDB Movies Dataset 2024 (1M Movies)           203MB  2024-11-24 09:38:29          13352        420  1.0
juzershakir/tmdb-movies-dataset                          TMDb Movies Dataset                                   3MB  2018-03-24 04:18:19           6275         55  0.7058824
ahsanaseer/top-rated-tmdb-movies-10k                     TMDB Movies Dataset                                   1MB  2022-07-26 15:45:13           4996         18  1.0
ursmaheshj/top-10000-popular-movies-tmdb-05-2023         Top 10000 popular Movies TMDB                         2MB  2023-06-13 16:29:49           2883         46  1.0
rounakbanik/the-movies-dataset                           The Movies Dataset                                  228MB  2017-11-10 02:40:38         373784       3648  0.8235294
alanvourch/tmdb-movies-daily-updates                     The Ultimate 1Million Movies Dataset (TMDB + IMDb)  249MB  2024-11-24 11:40:06           2298         57  1.0
asaniczka/full-tmdb-tv-shows-dataset-2023-150k-shows     Full TMDb TV Shows Dataset 2024 (150K Shows)         31MB  2024-04-05 15:44:41           2481        115  1.0
nagrajdesai/latest-10000-movies-dataset-from-tmdb        Latest 10000 Movies Dataset from TMDB                 1MB  2023-08-17 04:45:36           1356         42  1.0
akshaypawar7/millions-of-movies                          Movies Daily Update Dataset                         164MB  2024-11-18 01:16:44           8753        162  1.0
vishnurajyadav12/movies-dataset-tmdb                     Movies Dataset TMDB                                   1MB  2024-05-07 09:46:25            792         28  0.9411765
floatingcoder/tmdb-20000-movies-dataset                  Tmdb 20000 movies dataset 2023                      468KB  2023-07-17 15:44:29            848         36  1.0
muqarrishzaib/tmdb-10000-movies-dataset                  TMDB 10000 Movies Dataset                             1MB  2022-12-03 16:33:32            879         38  1.0
joebeachcapital/top-10000-most-popular-movies-from-imdb  Top 10000 Most Popular Movies from TMDB               2MB  2023-07-30 23:36:03           1114         37  1.0
ashvanths/toprated-tmdb-movies                           Top-Rated TMDB Movies                                 1MB  2022-08-15 06:49:17            775         33  1.0
aaditya1gautam/tmdb-top-rated-9000-movies-dataset        TMDB Top Rated 9000 Movies Dataset                    1MB  2024-09-25 05:48:09           1343         29  0.9411765
i0xc0d3x00000/tmdb-10000-movies-dataset                  TMDB 10000 Movies Dataset                             1MB  2023-03-02 14:05:50            881         28  1.0
darshanpatel3112/top-rated-movies-from-tmdb              Top Rated Movies  from TMDB                           1MB  2023-03-22 12:56:39            889         34  1.0
apkaayush/tmdb-10000-movies-dataset                      TMDB 10000 Movies Dataset                            52MB  2023-08-27 08:27:46            845         31  1.0
suchitakumari/tmdb-dataset-1990-2022                     TMDB_Dataset_1990_2022                              141KB  2022-06-11 14:19:36            252         32  1.0

In [166]:
!kaggle datasets download -d 'tmdb/tmdb-movie-metadata'

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.17 / client 1.6.12)
Dataset URL: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata
License(s): other
tmdb-movie-metadata.zip: Skipping, found more recently modified local copy (use --force to force download)

In [167]:
import zipfile
with zipfile.ZipFile('tmdb-movie-metadata.zip','r') as zip_ref:
    zip_ref.extractall('/Users/leonardoflores/Desktop/Project two')

In [168]:
#List all files and subdirectories
location = '/Users/leonardoflores/Desktop/Project two'
unzipped_files =os.listdir(location)
for file in unzipped_files:
    print(file)

.DS_Store
data_wrangling_project_starter (1).ipynb
tmdb_5000_credits.csv
tmdb_5000_movies.csv
tmdb-movie-metadata.zip
.ipynb_checkpoints

In [169]:
dataframe_one = pd.read_csv('tmdb_5000_credits.csv')
dataframe_one.set_index('movie_id',inplace=True)
dataframe_one.head(10)

,title,cast,crew
movie_id,,,
19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
559,Spider-Man 3,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
38757,Tangled,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
99861,Avengers: Age of Ultron,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
767,Harry Potter and the Half-Blood Prince,"[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
209112,Batman v Superman: Dawn of Justice,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."

In [170]:
dataframe_one.shape

(4803, 3)

#### Dataset 2

Type: CSV File.

Method: The data was gathered using the "Downloading files" manually method from "Kaggle.com". 


Dataset variables:

*   *Variable 1 FILL IN* (e.g., H_MEAN: Mean hourly wage)
*   *Variable 2 FILL IN*

In [171]:
#FILL IN 2nd data gathering and loading method
dataframe_two = pd.read_csv('tmdb_5000_movies.csv')
dataframe_two.set_index('id',inplace=True)
dataframe_two.head(10)

,budget,genres,homepage,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
id,,,,,,,,,,,,,,,,,,,
19995,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
206647,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond‚Äôs past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
49026,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
559,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
38757,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
99861,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
767,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
209112,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004

In [172]:
dataframe_two.shape

(4803, 19)

Optional data storing step: You may save your raw dataset files to the local data store before moving to the next step.

In [173]:
#Optional: store the raw data in your local data store

## 2. Assess data

Assess the data according to data quality and tidiness metrics using the report below.

List **two** data quality issues and **two** tidiness issues. Assess each data issue visually **and** programmatically, then briefly describe the issue you find.  **Make sure you include justifications for the methods you use for the assessment.**

### Quality Issue 1:

In [174]:
#FILL IN - Inspecting the dataframe visually
dataframe_one.head(10)

,title,cast,crew
movie_id,,,
19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
559,Spider-Man 3,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
38757,Tangled,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
99861,Avengers: Age of Ultron,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
767,Harry Potter and the Half-Blood Prince,"[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
209112,Batman v Superman: Dawn of Justice,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."

In [175]:
#FILL IN - Inspecting the dataframe programmatically
dataframe_one.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 19995 to 25975
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   4803 non-null   object
 1   cast    4803 non-null   object
 2   crew    4803 non-null   object
dtypes: object(3)
memory usage: 150.1+ KB

In [176]:
dataframe_one.isnull().sum()

title    0
cast     0
crew     0
dtype: int64

In [209]:
sum(dataframe_one.duplicated())

0

Issue and justification: 

Columns 'cast' and 'crew' contain JSON-like strings , which contains nested data. Within the nested data appear to contain important data such as  "cast_id" and "credit_id". Without pasing the columns with JSON values there will be an inability to answer my question to the fullest extent.

### Quality Issue 2:

In [177]:
#FILL IN - Inspecting the dataframe visually
dataframe_two.sample(10)

,budget,genres,homepage,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
id,,,,,,,,,,,,,,,,,,,
9801,50000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,"[{""id"": 212, ""name"": ""london england""}, {""id"":...",en,Bridget Jones: The Edge of Reason,Bridget Jones is becoming uncomfortable in her...,28.803802,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""FR"", ""name"": ""France""}, {""iso...",2004-11-10,40203020,108.0,"[{""iso_639_1"": ""de"", ""name"": ""Deutsch""}, {""iso...",Released,Same Bridget. Brand new diary.,Bridget Jones: The Edge of Reason,6.1,750
22832,40000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://ninja-assassin-movie.warnerbros.com/,"[{""id"": 441, ""name"": ""assassination""}, {""id"": ...",en,Ninja Assassin,"Ninja Assassin follows Raizo (Rain), one of th...",19.085403,"[{""name"": ""Studio Babelsberg"", ""id"": 264}, {""n...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2009-09-29,60462347,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Fear not the weapon, but the hand that wields it.",Ninja Assassin,6.2,371
2610,10284523,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,"[{""id"": 1361, ""name"": ""salesclerk""}]",en,Shopgirl,Mirabelle is a disenchanted salesgirl and aspi...,4.820166,"[{""name"": ""Epsilon Motion Pictures"", ""id"": 117...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-10-21,11588205,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Shopgirl,5.7,75
109414,32000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://www.thisistheend.com/,"[{""id"": 570, ""name"": ""rape""}, {""id"": 1299, ""na...",en,This Is the End,While attending a party at James Franco's hous...,38.217080,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-06-12,126041322,107.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Nothing ruins a party like the end of the world.,This Is the End,6.3,2359
9981,45000000,"[{""id"": 10749, ""name"": ""Romance""}, {""id"": 35, ...",NaN,"[{""id"": 494, ""name"": ""father son relationship""...",en,Kicking & Screaming,Phil Weston has been unathletic his entire lif...,8.992690,"[{""name"": ""Universal Pictures"", ""id"": 33}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-05-13,56070433,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,One man could lead this team to glory. . . Tha...,Kicking & Screaming,5.6,176
14112,7000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",NaN,"[{""id"": 255, ""name"": ""male nudity""}, {""id"": 59...",en,Auto Focus,"A successful TV star during the 1960s, former ...",7.051521,"[{""name"": ""Sony Pictures Classics"", ""id"": 58},...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-10-18,2062066,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A day without sex is a day wasted.,Auto Focus,6.1,56
8665,100000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",NaN,"[{""id"": 339, ""name"": ""submarine""}, {""id"": 2111...",en,K-19: The Widowmaker,When Russia's first nuclear submarine malfunct...,15.625949,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2002-07-19,35168966,138.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Fate has found its hero.,K-19: The Widowmaker,6.1,264
9693,76000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name...",http://www.universalstudiosentertainment.com/c...,"[{""id"": 318, ""name"": ""police state""}, {""id"": 4...",en,Children of Men,"In 2027, in a chaotic world in which humans ca...",35.387874,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2006-09-22,69959751,109.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The future's a thing of the past.,Children of Men,7.4,2071
4912,30000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 80, ""nam...",NaN,"[{""id"": 4688, ""name"": ""microfilm""}, {""id"": 556...",en,Confessions of a Dangerous Mind,"Television made him famous, but his biggest hi...",18.165957,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-12-30,33013805,113.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some things are better left top secret.,Confessions of a Dangerous Mind,6.6,275
9823,30000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 14, ""nam...",NaN,"[{""id"": 779, ""name"": ""martial arts""}, {""id"": 1...",en,Mortal Kombat: Annihilation,A group of heroic warriors has only six days t...,11.916389,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1997-11-21,51376861,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"The world was created in six days, so too shal...",Mortal Kombat: Annihilation,3.8,221

In [178]:
#FILL IN - Inspecting the dataframe programmatically
dataframe_two.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 19995 to 25975
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   keywords              4803 non-null   object
 4   original_language     4803 non-null   object
 5   original_title        4803 non-null   object
 6   overview              4800 non-null   object
 7   popularity            4803 non-null   float64
 8   production_companies  4803 non-null   object
 9   production_countries  4803 non-null   object
 10  release_date          4802 non-null   object
 11  revenue               4803 non-null   int64
 12  runtime               4801 non-null   float64
 13  spoken_languages      4803 non-null   object
 14  status                4803 non-null   object
 15  tagline               3959 non-null   object
 16  title                 4803 non-null   object
 17  vote_average          4803 non-null   float64
 18  vote_count            4803 non-null   int64
dtypes: float64(3), int64(3), object(13)
memory usage: 750.5+ KB

In [179]:
dataframe_two.isnull().sum()

budget                     0
genres                     0
homepage                3091
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [211]:
sum(dataframe_two.duplicated())

0

Issue and justification: 

Columns like 'genres' and 'production_companies' contain JSON-like strings, in other words they contain nested data. Pasing the columns with JSON values will deepen the understanding of our dataset. Without parsing, the data will have inconsistent data format which not allow the ability to have structured data. 

The 'homepage' and 'tagline' columns had a large amount of missing values.  Additional columns 'overview',release_date and 'runtime' only has a few missing values. These data gaps might affect our analysis later down in the visualization process. It would probably be best to drop 'homepage' and 'tagline' columns since there not relevent to the question that we want to answer.

### Tidiness Issue 1:

In [180]:
#FILL IN - Inspecting the dataframe visually
dataframe_one[dataframe_one['cast'].duplicated(keep=False)]

,title,cast,crew
movie_id,,,
17644,Barney's Great Adventure,[],"[{""credit_id"": ""52fe473b9251416c750921ff"", ""de..."
447027,Running Forever,[],[]
346081,Sardaarji,[],"[{""credit_id"": ""558ab3f4925141076f0001d7"", ""de..."
126509,2016: Obama's America,[],"[{""credit_id"": ""52fe4ae1c3a368484e16bcd7"", ""de..."
371085,Sharkskin,[],[]
325140,Hum To Mohabbat Karega,[],[]
361505,Me You and Five Bucks,[],[]
114065,Down & Out With The Dolls,[],[]
137955,Crowsnest,[],[]
102840,Sex With Strangers,[],[]
43630,The Helix... Loaded,[],[]
292539,Food Chains,[],"[{""credit_id"": ""5470c3b1c3a368085e000abd"", ""de..."
279759,Harrison Montgomery,[],[]
296943,The Hadza: Last of the First,[],"[{""credit_id"": ""54383e6fc3a36825ba001c52"", ""de..."
331493,Light from the Darkroom,[],[]
70875,The Harvest (La Cosecha),[],"[{""credit_id"": ""52fe4816c3a368484e0e8bbd"", ""de..."
14358,Mad Hot Ballroom,[],"[{""credit_id"": ""52fe45ea9251416c75066cd9"", ""de..."
294550,The Outrageous Sophie Tucker,[],"[{""credit_id"": ""55b26c8c9251411e0b0105e3"", ""de..."
380097,America Is Still the Place,[],[]
297100,The Little Ponderosa Zoo,[],[]
94072,Straight Out of Brooklyn,[],"[{""credit_id"": ""52fe49499251416c750c3167"", ""de..."
325579,Diamond Ruff,[],[]
328307,Rise of the Entrepreneur: The Search for a Bet...,[],[]
281189,Gory Gory Hallelujah,[],"[{""credit_id"": ""55135b3f9251412be400021e"", ""de..."
47546,I Want Your Money,[],[]
43743,Fabled,[],[]
87943,Sisters in Law,[],"[{""credit_id"": ""52fe49e39251416c910bc201"", ""de..."
73981,Ayurveda: Art of Being,[],"[{""credit_id"": ""52fe48b5c3a368484e106b4f"", ""de..."
300327,Death Calls,[],[]
378237,Amidst the Devil's Wings,[],[]
320435,UnDivided,[],[]
194588,Short Cut to Nirvana: Kumbh Mela,[],[]
287815,Call + Response,[],"[{""credit_id"": ""567b34d59251417ddf000e12"", ""de..."
126141,The Case of the Grinning Cat,[],"[{""credit_id"": ""52fe4ad8c3a368484e16a129"", ""de..."
37985,The Trials Of Darryl Hunt,[],"[{""credit_id"": ""57b638a4c3a3685f5a000562"", ""de..."
253290,Butterfly Girl,[],"[{""credit_id"": ""5305c66dc3a3685a711726c1"", ""de..."
335244,Antarctic Edge: 70¬∞ South,[],"[{""credit_id"": ""55327ddac3a3682217002e7f"", ""de..."
331745,Top Spin,[],"[{""credit_id"": ""551cad75c3a3684a2800155f"", ""de..."
38786,The Blood of My Brother: A Story of Death in Iraq,[],[]
64973,"Peace, Propaganda & the Promised Land",[],"[{""credit_id"": ""52fe46f6c3a368484e0ad693"", ""de..."
322745,Counting,[],"[{""credit_id"": ""54cdc726c3a3687f92003cad"", ""de..."
174362,Bending Steel,[],"[{""credit_id"": ""52fe4d49c3a36847f8258e35"", ""de..."
67238,Cavite,[],"[{""credit_id"": ""52fe475dc3a368484e0c319f"", ""de..."

In [181]:
#FILL IN - Inspecting the dataframe visually
dataframe_one[dataframe_one['crew'].duplicated(keep=False)]

,title,cast,crew
movie_id,,,
19615,Flying By,"[{""cast_id"": 1, ""character"": ""George"", ""credit...",[]
447027,Running Forever,[],[]
55831,Boynton Beach Club,"[{""cast_id"": 1, ""character"": ""Marilyn"", ""credi...",[]
371085,Sharkskin,[],[]
48382,"The Book of Mormon Movie, Volume 1: The Journey","[{""cast_id"": 1, ""character"": ""Sam"", ""credit_id...",[]
325140,Hum To Mohabbat Karega,[],[]
20653,Roadside Romeo,"[{""cast_id"": 1, ""character"": ""Romeo"", ""credit_...",[]
361505,Me You and Five Bucks,[],[]
114065,Down & Out With The Dolls,[],[]
137955,Crowsnest,[],[]
102840,Sex With Strangers,[],[]
43630,The Helix... Loaded,[],[]
357441,Karachi se Lahore,"[{""cast_id"": 0, ""character"": """", ""credit_id"": ...",[]
279759,Harrison Montgomery,[],[]
331493,Light from the Darkroom,[],[]
380097,America Is Still the Place,[],[]
297100,The Little Ponderosa Zoo,[],[]
325579,Diamond Ruff,[],[]
328307,Rise of the Entrepreneur: The Search for a Bet...,[],[]
47546,I Want Your Money,[],[]
43743,Fabled,[],[]
300327,Death Calls,[],[]
378237,Amidst the Devil's Wings,[],[]
325123,Teeth and Blood,"[{""cast_id"": 0, ""character"": ""Vincent Augustin...",[]
320435,UnDivided,[],[]
40963,Little Big Top,"[{""cast_id"": 0, ""character"": ""Seymour"", ""credi...",[]
194588,Short Cut to Nirvana: Kumbh Mela,[],[]
38786,The Blood of My Brother: A Story of Death in Iraq,[],[]

In [182]:
#FILL IN - Inspecting the dataframe programmatically
json.loads(dataframe_one['cast'].iloc[0])

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'Norm Spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'Joel David Moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'Moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'CCH Pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'Eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'Wes Studi',
  'order': 8},
 {'cast_id': 10,
  'character': "Tsu'Tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'Laz Alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'Dr. Max Patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'Dileep Rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'Lyle Wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'Matt Gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'Private Fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'Sean Anthony Moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'Cryo Vault Med Tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'Jason Whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'Venture Star Crew Chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'Scott Lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'Lock Up Trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'Kelly Kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'Shuttle Pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'James Patrick Pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'Shuttle Co-Pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'Sean Patrick Murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'Shuttle Crew Chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'Peter Dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'Tractor Operator / Troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'Kevin Dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'Dragon Gunship Pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'Kelson Henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'Dragon Gunship Gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'David Van Horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'Dragon Gunship Navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'Jacob Tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'Suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'Michael Blain-Rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'Suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'Jon Curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'Ambient Room Tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'Luke Hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'Woody Schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'Horse Clan Leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'Peter Mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'Link Room Tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'Sonia Yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'Basketball Avatar / Troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'Jahnel Curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'Basketball Avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'Ilram Choi',
  'order': 30},
 {'cast_id': 52,
  'character': "Na'vi Child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'Kyla Warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'Lisa Roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'Debra Wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'Chris Mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'Taylor Kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'Jodie Landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'Julie Lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'Cullen B. Madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'Joseph Brady Madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'Frankie Torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'Austin Wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'Sara Wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'Tamica Washington-Miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'Lucy Briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'Nathan Meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'Gerry Blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'Matthew Chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'Paul Yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'Op Center Duty Officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'Wray Wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'James Gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'Melvin Leno Clark III',
  'order': 51},
 {'cast_id': 73,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'Carvon Futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'Brandon Jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'Micah Moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'Hanniyah Muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'Christopher Nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'Christa Oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'April Marie Thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'Bravita A. Threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'Mining Chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'Colin Bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'Veteran Miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'Mike Bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'Richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'Matt Clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "Nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'Nicole Dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'Jamie Harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'Allan Henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'Ground Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'Anthony Ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'Flight Crew Mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'Ashley Jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'Samson Pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'Dean Knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'Joseph Mika-Hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'Banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'Terry Notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'Soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'Kai Pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'Blast Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'Logan Pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'Vindum Raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'Stuart Pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'Hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'Raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'Ops Centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'Gareth Ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'Engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'Rhian Sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "Col. Quaritch's Mech Suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 'T. J. Storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'Female Marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'Jodie Taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'Ikran Clan Leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'Alicia Vela-Bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'Geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'Richard Whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "Na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'Nikie Zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'Julene Renee',
  'order': 82}]

In [183]:
#FILL IN - Inspecting the dataframe programmatically
json.loads(dataframe_one['crew'].iloc[0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [184]:
dataframe_one.columns

Index(['title', 'cast', 'crew'], dtype='object')

Issue and justification: 

As described in this section of advanced data wrangling, there are three key principles that data structures should adhere too. These rules are each variable should have its own column, each observation should have its own row, and lastly each type of obervational unit should form a separate table.

With this in mind, once we properly parse through the JSON columns, we will have multiple observational units one table. This can create issues with our analysis of the data and the repeated 'movie_id' will introduce unwanted redundancy. We must seperate the tables into the 'movie' table and two additional tables for each column that has JSON values. In order words, an additional tables name 'cast' and 'crew'.

### Tidiness Issue 2:

In [185]:
#FILL IN - Inspecting the dataframe visually
dataframe_two[dataframe_two['production_companies'].duplicated(keep=False)]

,budget,genres,homepage,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
id,,,,,,,,,,,,,,,,,,,
285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
559,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
38757,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
767,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14337,7000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.primermovie.com,"[{""id"": 1448, ""name"": ""distrust""}, {""id"": 2101...",en,Primer,Friends/fledgling entrepreneurs invent a devic...,23.307949,"[{""name"": ""Thinkfilm"", ""id"": 446}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-10-08,424760,77.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What happens if it actually works?,Primer,6.9,658
67238,0,"[{""id"": 10769, ""name"": ""Foreign""}, {""id"": 53, ...",NaN,[],en,Cavite,"Adam, a security guard, travels from Californi...",0.022173,[],[],2005-03-12,0,80.0,[],Released,NaN,Cavite,7.5,2
9367,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
72766,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
126186,0,[],http://shanghaicalling.com/,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7

In [186]:
#FILL IN - Inspecting the dataframe visually
dataframe_two[dataframe_two['spoken_languages'].duplicated(keep=False)]

,budget,genres,homepage,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
id,,,,,,,,,,,,,,,,,,,
19995,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
49026,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
559,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9367,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
72766,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
231617,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
126186,0,[],http://shanghaicalling.com/,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
25975,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [187]:
#FILL IN - Inspecting the dataframe programmatically

json.loads(dataframe_two['production_companies'].iloc[0])

[{'name': 'Ingenious Film Partners', 'id': 289},
 {'name': 'Twentieth Century Fox Film Corporation', 'id': 306},
 {'name': 'Dune Entertainment', 'id': 444},
 {'name': 'Lightstorm Entertainment', 'id': 574}]

In [188]:
#FILL IN - Inspecting the dataframe programmatically
json.loads(dataframe_two['spoken_languages'].iloc[0])

[{'iso_639_1': 'en', 'name': 'English'},
 {'iso_639_1': 'es', 'name': 'Espa√±ol'}]

In [189]:
dataframe_two.columns

Index(['budget', 'genres', 'homepage', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

Issue and justification: 

On 'production_companies' column each column should have its own column for analysis. Currently the column has nested structure which violates the tidiness priciple of 'one variable per column'. Therefore it needs to be properly parse through. On 'spoken_languages' column, we are able to see that multiple values are within a single cell. This creates issues for say if we want to filter our analysis through grouping of languages.

## 3. Clean data
Clean the data to solve the 4 issues corresponding to data quality and tidiness found in the assessing step. **Make sure you include justifications for your cleaning decisions.**

After the cleaning for each issue, please use **either** the visually or programatical method to validate the cleaning was succesful.

At this stage, you are also expected to remove variables that are unnecessary for your analysis and combine your datasets. Depending on your datasets, you may choose to perform variable combination and elimination before or after the cleaning stage. Your dataset must have **at least** 4 variables after combining the data.

In [236]:
# FILL IN - Make copies of the datasets to ensure the raw dataframes are not impacted
df1 = dataframe_one.copy()
df2 = dataframe_two.copy()

In [237]:
df1.head()

,title,cast,crew
movie_id,,,
19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [238]:
df2.head()

,budget,genres,homepage,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
id,,,,,,,,,,,,,,,,,,,
19995,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
206647,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond‚Äôs past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
49026,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

### **Quality Issue 1: FILL IN**

In [243]:
# FILL IN - Apply the cleaning strategy
df1['cast']

movie_id
19995     [{"cast_id": 242, "character": "Jake Sully", "...
285       [{"cast_id": 4, "character": "Captain Jack Spa...
206647    [{"cast_id": 1, "character": "James Bond", "cr...
49026     [{"cast_id": 2, "character": "Bruce Wayne / Ba...
49529     [{"cast_id": 5, "character": "John Carter", "c...
                                ...
9367      [{"cast_id": 1, "character": "El Mariachi", "c...
72766     [{"cast_id": 1, "character": "Buzzy", "credit_...
231617    [{"cast_id": 8, "character": "Oliver O\u2019To...
126186    [{"cast_id": 3, "character": "Sam", "credit_id...
25975     [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4803, dtype: object

In [246]:
info = pd.json_normalize(df1['cast'])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (1139258280.py, line 2)

In [233]:
normalized_df1 =  df1.columns
normalized_df1

Index(['title', 'cast', 'crew'], dtype='object')

In [155]:
# FILL IN - Validate the cleaning was successful

Justification: 

Now that we copy our first dataframe, it is time to address the quality of the dataset. As stated earlier, the dataset contained JSON data. It needed to be parsed throughly for futher analysis. The way I did this process was explained step by step in the cell above.

### **Quality Issue 2: FILL IN**

In [ ]:
#FILL IN - Apply the cleaning strategy

In [ ]:
#FILL IN - Validate the cleaning was successful

Justification: *FILL IN*

### **Tidiness Issue 1: FILL IN**

In [ ]:
#FILL IN - Apply the cleaning strategy
df1 = df1.drop(columns = 'crew' , inplace= True)

In [ ]:
#FILL IN - Validate the cleaning was successful
df1.head

Justification: *FILL IN*
Decided that instead of normalizing the 'crew' column, I would instead drop the column as it has multiple observational units that is not relevent to my problem. By doing this it will enchance the tidiness of the dataset.

### **Tidiness Issue 2: FILL IN**

In [1]:
#FILL IN - Apply the cleaning strategy

In [2]:
#FILL IN - Validate the cleaning was successful

Justification: *FILL IN*

### **Remove unnecessary variables and combine datasets**

Depending on the datasets, you can also peform the combination before the cleaning steps.

In [ ]:
#FILL IN - Remove unnecessary variables and combine datasets

## 4. Update your data store
Update your local database/data store with the cleaned data, following best practices for storing your cleaned data:

- Must maintain different instances / versions of data (raw and cleaned data)
- Must name the dataset files informatively
- Ensure both the raw and cleaned data is saved to your database/data store

In [ ]:
#FILL IN - saving data

## 5. Answer the research question

### **5.1:** Define and answer the research question 
Going back to the problem statement in step 1, use the cleaned data to answer the question you raised. Produce **at least** two visualizations using the cleaned data and explain how they help you answer the question.

*Research question:* FILL IN from answer to Step 1

In [ ]:
#Visual 1 - FILL IN

*Answer to research question:* FILL IN

In [ ]:
#Visual 2 - FILL IN

*Answer to research question:* FILL IN

### **5.2:** Reflection
In 2-4 sentences, if you had more time to complete the project, what actions would you take? For example, which data quality and structural issues would you look into further, and what research questions would you further explore?

*Answer:* FILL IN